# Limits imposed by Discord.
class Limits:

    MESSAGE_CHARACTER_LIMIT = 2000

    EMBED_CHARACTER_LIMIT = 6000

    EMBED_TITLE_LIMIT = 256

    EMBED_DESCRIPTION_LIMIT = 4096

    EMBED_FIELD_LIMIT = 25

    EMBED_FIELD_NAME_LIMIT = 256

    EMBED_FIELD_VALUE_LIMIT = 1024

    EMBED_FOOTER_TEXT_LIMIT = 2048

    EMBED_AUTHOR_NAME_LIMIT = 256

    EMBED_INLINE_FIELD_LIMIT = 3

    BOT_EMBEDS_PER_MESSAGE_LIMIT = 1

    WEBHOOK_EMBEDS_PER_MESSAGE_LIMIT = 10
