# Defines all music commands and soundplayers for servers

# NOTE: ALL TAKES PLACE WITHIN SERVER'S RESPECTIVE SOUNDPLAYER
# PLAY WILL START PLAYING FROM THE QUEUE - DON'T PLAY IF ALREADY PLAYING
# QUEUE WILL ADD TO QUEUE (WITH START/END TIMESTAMP)
# STOP WILL END THE CURRENTLY PLAYING AUDIO (SOFT STOP, IDEALLY)
# NEXT WILL PLAY NEXT IN QUEUE
# CLEAR QUEUE WILL REMOVE ALL SONGS
# REMOVE LINK WILL REMOVE THE GIVEN LINK FROM QUEUE
# REMOVE BY ITSELF WILL REMOVE CURRENT PLAYING OR FRONT OF QUEUE ITEM
# VOLUME # CHANGES VOLUME
# CURR VOLUME DISPLAY VOLUME
# FFW
# SKIP ONTO NEXT TRACK
# LEAVE WILL MAKE IT STOP TRACK, CLEAR QUEUE, LEAVE
# JOIN PLAYS CURRENT QUEUE
# NOW PLAYING
# DEQUEUE # ?
