from enum import Enum


class ListenTo(Enum):
    ON_MESSAGE = 0
    ON_MESSAGE_DELETE = 1
    ON_MESSAGE_EDIT = 2
    ON_REACTION_ADD = 3
    ON_REACTION_REMOVE = 4
    ON_REACTION_CLEAR = 5
    ON_CHANNEL_DELETE = 6
    ON_CHANNEL_CREATE = 7
    ON_CHANNEL_UPDATE = 8
    ON_MEMBER_JOIN = 9
    ON_MEMBER_REMOVE = 10
    ON_MEMBER_UPDATE = 11
    ON_SERVER_JOIN = 12
    ON_SERVER_REMOVE = 13
    ON_SERVER_UPDATE = 14
    ON_SERVER_ROLE_CREATE = 15
    ON_SERVER_ROLE_DELETE = 16
    ON_SERVER_ROLE_UPDATE = 17
    ON_SERVER_EMOJIS_UPDATE = 18
    ON_SERVER_AVAILABLE = 19
    ON_SERVER_UNAVAILABLE = 20
    ON_VOICE_STATE_UPDATE = 21
    ON_MEMBER_BAN = 22
    ON_MEMBER_UNBAN = 23
    ON_TYPING = 24
    ON_GROUP_JOIN = 25
    ON_GROUP_REMOVE = 26
